### PR TITLE
axum 0.7.5

### PR DESCRIPTION
**Pull request by xxkeming**

### CODE REVIEW

**Comment by minghuaw** [comment]
Would you mind update the integration test for axum as well (https://github.com/minghuaw/toy-rpc/blob/main/toy-rpc/tests/axum_integration.rs)?

**Comment by xxkeming** [comment]
ok!!

**Comment by minghuaw** [comment]
Thanks, I will review this in about an hour

**Comment by minghuaw** [comment]
Merged. This should probably be considered a breaking change. I will update other deps and make a breaking release probably tomorrow

**Pull request merged**
